/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ztysdmy.bloomfilter;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
    
    	int one = 1;
    	int two = one<<1;
    	System.out.println(Integer.numberOfTrailingZeros(two));
    }
}
