/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ztysdmy.bloomfilter;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
    
    	var cache = 1l;
    	var mask = 1l<<2;
    	
    	cache = cache|mask;
    	
    	var mask2 = 1l<<2;
    	
    	System.out.println((cache&mask2)==0);
    	
    }
}
