/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ztysdmy.bloomfilter;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
    
    	var one = 0l;
    	var two = 1l;
    	System.out.println((one|two));
    }
}
